wallpaper {
monitor = eDP-1
path = /home/rraks/Pictures/wallpapers/gruv-abstract.png
fit_mode = cover
}

splash = false
ipc = off

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
ipc = off

